set :domain, '106.75.14.116'
set :deploy_to, '/data/lijia_staging'
set :repository, 'git@github.com:lijiazhengli/lijia_admin.git'
set :branch, 'T2-staging'
set :user, 'root'
set :rails_env, 'staging'
